apiVersion: v1
kind: Service
metadata:
  name: flask-todo-service
  labels:
    app: todo-app
    tier: frontend
spec:
  type: NodePort 
  ports:
    - port: 80 
      targetPort: 5000 
  selector:
    app: todo-app
    tier: frontend