apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: todo-app
    tier: database
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: todo-app
    tier: database
  type: ClusterIP